# Generated by Django 5.1.2 on 2024-10-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Продавцы',
            fields=[
                ('номер_чека', models.IntegerField(primary_key=True, serialize=False)),
                ('дата_покупки', models.DateField()),
                ('номер_кассы', models.IntegerField()),
                ('продавец', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Товары',
            fields=[
                ('номер_товара', models.IntegerField(primary_key=True, serialize=False)),
                ('наименование', models.CharField(max_length=255)),
                ('единица_измерения', models.CharField(max_length=255)),
                ('цена', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Чеки',
            fields=[
                ('номер_чека', models.IntegerField(primary_key=True, serialize=False)),
                ('номер_товара', models.IntegerField()),
                ('количество', models.IntegerField()),
                ('стоимость', models.IntegerField()),
            ],
        ),
    ]
