# Generated by Django 5.1.3 on 2024-12-20 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_билеты_клиенты_фильмы_delete_продавцы_delete_товары_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Группа',
            fields=[
                ('id_group', models.IntegerField(primary_key=True, serialize=False)),
                ('name_teacher', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Заведующие',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_teacher', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Категория',
            fields=[
                ('id_category', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Билеты',
        ),
        migrations.DeleteModel(
            name='Клиенты',
        ),
        migrations.DeleteModel(
            name='Фильмы',
        ),
        migrations.AddField(
            model_name='группа',
            name='id_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.категория'),
        ),
    ]
