# -*- coding: utf-8 -*-
"""oiis_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ySCmvkbfzMtz8SqrntSDs7M17fxVr7P5
"""

!pip install ultralytics roboflow opencv-python --quiet

import torch, ultralytics, roboflow, os, cv2
from ultralytics import YOLO

from roboflow import Roboflow
from ultralytics import YOLO
rf = Roboflow(api_key="AnQbLkQeH26zFaNvRRv9")
project = rf.workspace("roboflow-100").project("vehicles-q0x2v")
version = project.version(2)
dataset = version.download("yolov11")

model = YOLO("yolo11s.pt")

!pip install yt-dlp --quiet

!yt-dlp -f "mp4" -o "video.mp4" https://www.youtube.com/shorts/0u1pWplwpc8

import os
if os.path.exists("video.mp4"):
    print("Видео успешно скачано!")
else:
    print("Ошибка: видео не скачано.")

from IPython.display import Video
Video("video.mp4", embed=True)

!apt install ffmpeg -y

from ultralytics import YOLO
import torch

model = YOLO("yolo11s.pt")

results_bot = model.track(
    source="video.mp4",
    tracker="botsort.yaml",
    save=True,
    stream=False,
    vid_stride=1,
    conf=0.25,
    device=0 if torch.cuda.is_available() else 'cpu',
    name="botsort_run",
    project="runs/track"
)

results_byte = model.track(
    source="video.mp4",
    tracker="bytetrack.yaml",
    stream=True,
    show=False,
    save=True,
    conf=0.25,
    device=0 if torch.cuda.is_available() else 'cpu'
)