# -*- coding: utf-8 -*-
"""iad_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QqZP4gO9Cs6z0RH-Kvl8x_mQAWCqMaht
"""

pip install ucimlrepo

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from ucimlrepo import fetch_ucirepo
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

from sklearn.neural_network import BernoulliRBM
from tqdm import tqdm

maternal_health_risk = fetch_ucirepo(id=863)
X = maternal_health_risk.data.features
y = maternal_health_risk.data.targets

le = LabelEncoder()
y = le.fit_transform(y.values.ravel())

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

def build_model():
    model = Sequential([
        Input(shape=(X_train.shape[1],)),
        Dense(64, activation='relu'),
        Dense(32, activation='relu'),
        Dense(3, activation='softmax')
    ])
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

model_base = build_model()
history_base = model_base.fit(X_train, y_train, epochs=50, batch_size=16, validation_split=0.2, verbose=0)

y_pred_base = np.argmax(model_base.predict(X_test), axis=1)
print("Точность без предобучения:", accuracy_score(y_test, y_pred_base))
print(classification_report(y_test, y_pred_base))

rbm1 = BernoulliRBM(n_components=64, learning_rate=0.05, n_iter=15, random_state=42, verbose=True)
rbm2 = BernoulliRBM(n_components=32, learning_rate=0.05, n_iter=15, random_state=42, verbose=True)

X_rbm1 = rbm1.fit_transform(X_train)

X_rbm2 = rbm2.fit_transform(X_rbm1)

print("Форма после RBM:", X_rbm2.shape)

model_rbm = Sequential([
    Input(shape=(X_train.shape[1],)),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(3, activation='softmax')
])

model_rbm.layers[0].set_weights([rbm1.components_.T, np.zeros(64)])
model_rbm.layers[1].set_weights([rbm2.components_.T, np.zeros(32)])

model_rbm.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

history_rbm = model_rbm.fit(X_train, y_train, epochs=50, batch_size=16, validation_split=0.2, verbose=0)

y_pred_rbm = np.argmax(model_rbm.predict(X_test), axis=1)
print("Точность после предобучения RBM:", accuracy_score(y_test, y_pred_rbm))
print(classification_report(y_test, y_pred_rbm))

