# -*- coding: utf-8 -*-
"""smzks_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mj_tQyZx413T_tKsw7NLVtBRyZ6z4TTi
"""

!pip install qiskit qiskit-aer pylatexenc -q

from qiskit import QuantumCircuit
from qiskit_aer import Aer
from qiskit.visualization import plot_bloch_multivector

"""S=A⊕B⊕X

C=(A∧B)∨(X∧(A⊕B))
"""

qc = QuantumCircuit(5, 2)

qc.cx(0, 3)
qc.cx(1, 3)
qc.cx(2, 3)
qc.barrier()

qc.ccx(0, 1, 4)
qc.ccx(2, 3, 4)

qc.measure(3, 0)
qc.measure(4, 1)

qc.draw('mpl')

"""F(A, B, C, D, E) = (A ∧ B) ∨ (C ∧ D) ∨ (E ∧ (A ⊕ B))

x
"""

qc2 = QuantumCircuit(7, 1)

qc2.cx(0, 6)  #(A ⊕ B)
qc2.cx(1, 6)

qc2.cx(0, 5)
qc2.cx(1, 5)
qc2.ccx(4, 5, 6)  #(E ∧ (A ⊕ B)

qc2.ccx(0, 1, 6)  #(A ∧ B)

qc2.ccx(2, 3, 6) #(C ∧ D)

qc2.measure(6, 0)

qc2.draw("mpl")